### ISSUE TITLE
Förslag: Svenskt datumformat

### ISSUE THREAD

**Issue by EniacData** [ROWSAB/Booking-Nordic-Standard#1]
Eniac föreslår att svenskt datumformat används som standard. Den dagen bokningen inträffar avgör om det är sommartid eller inte som gäller. Dvs om bokningen inträffar mellan klockan 11 och kl 13 så skickar vi 11:00-13:00 och inget annat.

**Comment by ROWSAB** [comment]
ROWS föreslår att vi kör på GMT av två själ.
1. Vi låser inte denna standard till just Sverige och Norge.
   Så som jag ser det så är "placeringen" av bokningssystemet oväsentligt och om man tänker stort så är det ett BAS som egentligen kan spänna över flera tidszoner. (Stora kunder)
   Placeringen av resursen är om något det enda som borde kunna anses vara lokal tid.
   Därmed måste det som BCS får in som data vara en så ren tid som möjligt. 
2. Grundtanken med tidszoner och lösningen med tidszoner är att själva systemet ska i grunden alltid arbeta med GMT och det är inte förrän tiden presenteras för användaren (GUI) som rätt tidszon skall appliceras. Det har jag fått lära mig den hårda vägen. Så alla tider som skickas i vårt system är GMT.

Så GMT ger därför mycket mindre risk för fel när/om man behöver tillämpa tidszonshantering.
Och det blir därmed mycket mer enhetligt i programmeringsväg om man alltid hanterar tid som GMT och sedan presenterar tiden för användaren i den tidszonen användaren själv vill. Det är således så som operativsystemen har löst det. Själva klockan går från 0 och framåt. Den ska inte och bör inte hoppa fram 3600 sekunder så fort det blir sommartid och minska med 3600 när det blir vintertid.

Sen kom jag precis på att om vi får in "lokal" tid. (Detta bör betraktas som lokal tid å inte svensk tid) så måste varje server som hämtar data vara inställd på svensk tid. Annars blir det tokfel. Vad händer om en BCS vill använda samma server för att hämta data från ett svenskt BAS och ett finskt BAS?
Då börjar tidszonshanteringen bli ett problem, och dessa problem är en mardröm. Finns massor av artiklar på nätet om det. Och lösningen har, av vad jag sett, alltid varit att hantera tid som GMT, alltid. Och sen låta användaren själv bestämma vilken tidzon som tiden ska presenteras i, oftast är det inställningen i operativsystemet som gäller.

**Comment by EniacData** [comment]
Förtydligande: Eniac föreslår att tiden för en bokning skickas i det lokala tidsformat som gäller där den bokade lokalen finns den bokade dagen. Vi menade inte att låsa ute andra länder!

En anledning är att vi har haft precis motsatta problem, nämligen ett system som bara tar emot GMT, och så har någon av alla användarnas datorer i systemet varit inställd på engelska, och denna dator har översatt de bokade tiderna fel innan de skickats (Aveny använder lokal tid internt).

En annan är att det är det naturliga formatet. Användaren bokar kl 13. Systemet skickar kl 13. Lokalen värms kl 13. Skall tiderna översättas fram och tillbaka under transaktionen försvåras felsökning.

Ett BCS som internt använder GMT kan ju bara transformera tiden innan den sparas internt i databasen.
Ett BAS som internt använder GMT måste transformera tiden innan den skickas, och riskerar därmed motsvarande problem som jag beskrev ovan. Aveny använder som sagt lokal tid internt, så lokal tid skulle förenkla för oss.

**Comment by JEFFBjorn** [comment]
Tycker detta är ett typexempel på där vi skall ha en omröstning i enligt "den demokratiska modellen".

Jag(JEFF) och Robin(Rows) diskuterade detta och just tidsformatet där lokalen står var ett av förslagen som diskuterades. Det skulle vara intressant och se vad alla andra tycker.

//Björn
Jeff Electronics AB

**Comment by ROWSAB** [comment]
Eniac: GMT är mycket lättare att jobba med för oss när man tänker på att detta ska vara en öppen standard.

Antingen får vi skriva in i standarden att BCS ska ta ett antagande att alla tider som skickas är med svensk tid med korrekt sommar/vintertid. Och då konvertera tiden på ett antagande, vilket är dålig practise.

Eller så får BCS ha en inställning där det ställs in vilket tidsformat just den aktuella BASen kör med. Vilket är en onödig inställning

Eller så får BCS anta att tider från en BAS alltid är samma tidszon som lokalen finns på. Vilket mycket väl kan bli fel i framtiden. Kanske inte mellan eniac och ROWS eller Eniac och JEff, men som en standard är det också bad practise.

Eller så får BAS skicka med vilken tidsskillnad det är från GMT (se v001 av dokumentet) Då innebär det att vi får in 1 på vintern och 2 på sommaren.

Men alla dessa exemplen blir grymt komplicerat när BCS enhet/server inte är inställd på svensk tid. 
Det är mycket mycket lättare för BAS att skriva tiden i GMT när responsen skapas. Eftersom BAS vet med all säkerhet exakt vilken tidszon som den aktuella tiden avser. Ingen "konvertering" krävs. Det enda som krävs är att datum objektet skrivs ut som UTC.

Därför har jag lagt som förlsag att köra med epoch tider istället för en sträng som människor kan läsa.
Jeff ville dock ha sträng i debugging syfte. = Lättare att se vad som har blivit fel om någon har bokat fel tex. Vilket jag kan hålla med om.

Ang epoch se denna länk: http://www.epochconverter.com/
Den har jag använt mycket för att verifiera mina bokningar så att epoch stämmer.

**Comment by ROWSAB** [comment]
VI kan väl rösta här?
ROWS röstar för GMT

**Comment by EniacData** [comment]
Jag har full förståelse för att byte till lokal tid kan bli besvärligt i ett befintligt system.

Men om man tänker ur ett användarperspektiv så är det mycket enklare med lokal tid.
Antag t.ex. att servicebyrån i Stockholm beslutar sig för att agera bokningscentral för Stockholms församlingar, och att de även inkluderar Sjömanskyrkan i London. Antag vidare att de anlitar ett multinationellt BCS att sköta uppvärmningen i sina lokaler. Så ringer Britt och ber att få boka en vigsel första juli kl 11 i London.

Om BAS och BCS nu är ense om lokal tid är saken klar. 11 skickas. 11 värms lokalen upp.

Om GMT skall användas måste antingen bokaren veta att boka lokalen kl 9 (eller vad det nu blir) eller så måste lokalen ha en tidszon knuten i BAS och konvertera 11 svensk tid till 11 lokal tid. Är lokalen i Sverige måste 11 konverteras till GMT i BAS och sedan konverteras tillbaka till 11 svensk tid i BCS.
Skall sedan en gemensam kalender öppnas för Sjömanskyrkan och S:t Clara så behöver BAS verkligen hålla tungan i rätt mun.

Hade alla bara skickat och sparat klockslagen i textformat hade ingen haft några problem och inga fel hade kunnat uppstå (förutsatt att klockan i själva värmestyrningsapparaten är rätt inställd). imho.
Jämför med att skicka ett SMS till vaktmästaren i London: "Vigsel kl 11, slå på värmen kl 7".

Hade BCS varit någon slags centralt system som samordnade tider i olika lokaler på något sätt hade det varit en annan sak. Men nu är varje uppvärmning en begäran för en enda lokal vid ett enda tillfälle, och inga andra lokaler eller tider påverkas.

Eniac röstar för lokal tid

**Comment by ROWSAB** [comment]
Mjo, men användaren ska ju inte vara inblandad i valet av tidszon som skickas mellan BAS och BCS väl?
Om ni väljer att låta Britt boka en kyrka i London så är det upp till er och avgöra hur hon ska välja rätt tid. 
Det bör ju inte vara något som BCS ska bli inbladdad i.
Om ni vet vilket tid hon vill att det ska bli varmt så vet ni också per automatik vilken tid det är uttryckt i UTC. Det blir mycket mer komplicerat om BCS också ska veta vad hon menar.

**Comment by ROWSAB** [comment]
Ska vi testa en röstning här?
Dom som vill köra lokal tid kör tumme UPP på denna kommentar.
Dom som vill köra på GMT kör tumme NER på denna kommentar.

(OBS! Redigerade kommentaren så att tumme upp blir lika med förslaget i issue:n)

**Comment by EniacData** [comment]
Sorry, jag röstade fel (och det tror jag att Rows också gjorde) och trodde att det bara var att ändra.

Nytt försök:
Tumme UPP för GMT.
Tumme NER för lokal tid.

**Comment by ROWSAB** [comment]
Ah fan det går ju inte å ändra sin röst på detta sätt :(

**Comment by ljniklas** [comment]
Nu ska jag komma här och föreslå ett tredje alternativ, bara för att göra förvirringen total, hehe.

Men vad sägs som att följa en redan etablerad standard? ISO-8601 (ATOM): [https://sv.wikipedia.org/wiki/ISO_8601](https://sv.wikipedia.org/wiki/ISO_8601)
Denna utgår ifrån UTC och inte tidzonen GMT. För om vi inte ska använda Sveriges tidszon (CET?) så tycker jag inte att vi ska använda GMT heller. Lite kring skillnaden mellan GMT och UTC: [https://www.timeanddate.com/time/gmt-utc-time.html](https://www.timeanddate.com/time/gmt-utc-time.html) 

Annars har jag ingen direkt åsikt då jag med enkelhet kan konvertera våra tider till det som bestäms i standarden.

**Comment by ljniklas** [comment]
Inser nu att ISO-8601 är bara ett format. Vi måste ändå komma överens om vilken tidszon som ska användas. Vilket inte spelar mig någon större roll egentligen, men då det är en nordisk standard vi ska ta fram så känns CET rimligt då 3/5 nordiska länder använder denna.

**Comment by ROWSAB** [comment]
Mjo, men Eniac pratar om lokal tidszon vs GMT.
Lokal tidszon är inte bestämt att det är svensk tidszon.
Därför tycker jag att det absolut enklaste är att ta bort tidszon begreppet helt och alltid skicka tid baserad på tidzon +0 alltså GMT. Epoch eller Unix Epoch hade jag föredragit, men är öppen för att skicka det som en sträng med datum och tid istället.

**Comment by ROWSAB** [comment]
För det är inte bara en fråga om tidszon +1 eller +0 när vi pratar svensk tid eftersom vi måste ta hänsyn till sommar vs vintertider. Halva året kör vi i Sverige +2 andra halvan +1

Edit: Vi kan också lika väl konvertera svensk tid till epoch. Men detta är en fråga om enkelheten i standarden. Det vi får göra i sådana fall är att först parsa ut strängen som UTC och sedan dra bort 3600s om det är vintertid och (3600 \* 2) om det är sommartid för att få ut ren UTC.
Därav hade det varit mycket bättre att skicka med vilken tidszonsskillnad tiden avser (se v001)
Detta skall då göras i ANSI C. Vi är precis som Jeff mer på hårdvarunära än vad dom flesta här är.

Jag har för övrigt alltid sett GMT och UTC som samma. Vet ej om det är lämpligt.

**Comment by ljniklas** [comment]
Men oavsett om CET/CEST eller GMT används så måste konvertering ske någonstans. Det kommer vi aldrig ifrån.
Men lokal tid så som Eniac föreslår känns inte som det platsar i en standard faktiskt, det kan jag hålla med om.

**Comment by ROWSAB** [comment]
Absolut är det så och då föreslår jag att konverteringen sker där tiden sätts. Alltså i det system som vet vilken tidszon tiden avser. Annars måste den informationen skickas med tillsammans med tidsstämpeln.

**Comment by ROWSAB** [comment]
Alltså om vi i Nivå 2 tex vill lägga in stöd för att kunna skapa bokningar i BCS som ska upp till BAS så ska tiden skickas i samma format/tidszon som standarden bestämmer.

**Comment by ROWSAB** [comment]
Förresten så kom jag på att man kan lägga fram det så att tidszon är ett begrepp för oss människor.
För ett system är tidszon helt oväsentligt. Systemet vill veta hur rotationen och plaseringen av jorden ska vara i förhållande till solen när klockorna i en kyrka ska ringa.....typ ;)
Datorn ska strunta i vad klockan på armen på Birgitta säger.
Däremot så är BAS väldigt intresserad av vad Birgitta menar när hon säger att det ska ringa en viss tid. Menar hon svensk tid eller kinesisk tid (om hon nu skulle befinna sig där för tillfället)

**Comment by EniacData** [comment]
Frågan är väl vem som ska bry sig om tidszonen.
Med lokal tid är det bara att ställa in tiden timern i kyrkklockan rätt.
Skall tidszoner användas måste någon i BAS fatta beslutet. Är det rimligt att skjuta över problemet på slutanvändarna bara för att det annars inte "platsar i en standard"?

**Comment by ROWSAB** [comment]
Men då förutsätter du att enheten i kyrkan är den som hämtar.
Det kan lika väl vara en server, eller flera servrar utplacerade runt om i världen.
Om en BCS server ska hämta från BAS från både sverige och finland så får vi problem.
Lokal tid går inte att sätta i den servern. Lokal tid ska inte hanteras i servern, det ska hanteras i GUI.

Detta blir inte ett problem för användaren bara för att BAS skriver ner tiden i UTC vid varje fråga.
Det har inget med användaren att göra.

**Comment by ljniklas** [comment]
Håller med Robin.

Om jag i BAS låter mina användare välja klockslag i CET/CEST och sen rapporterar detta till BCS som UTC så rör det inte användaren. Bara jag vet vad BAS-systemet är inställt på och skillnaden är gentemot UTC vid konvertering.

**Comment by JEFFBjorn** [comment]
Vi från JEFF anser nog att man alltid ska utgå ifrån användaren.
Tänker man ur användarens synvinkel så vill denna boka kl 11:00 svensk tid på en söndag så vill användaren skriva in 11:00, ALLTID, oavsett om användaren befinner sig i Thailand eller i Sverige eller om det är sommar eller vintertid osv. När användaren sedan tittar på vad som är bokat så är det självklart att användaren skall se kl 11:00.

Samma resonemang finns oavsett i vilket system man bokar. Vi erbjuder användaren att kunna boka i BAS och BCS och DUC.

Att hålla på och konventera fram och tillbaka i varje steg ser vi på JEFF som helt onödigt och därför förordar vi att man använder lokal tid i standarden.

**Comment by EniacData** [comment]
Jag förutsätter inte att enheten i kyrkan hämtar. Jag förutsätter bara att ingen rör klockslaget som mitt BAS skickar in innan det kommer fram till enheten i kyrkan. Om BCS lagrar klockslaget som en varchar(5) eller som en datetime spelar ingen roll så länge kyrkenheten kan läsa av det i samma format som servern fick det (dvs. om du får 10:50 och puttar in det som GMT och läser ut det som GMT så spelar det ingen roll om det egentligen var CET). Klockslaget är enbart ett meddelande från bokaren till enheten i kyrkan. Ingen annan behöver lägga sig i innehållet. Än mindre ändra i det.

Som programmerare förstår jag mycket väl hur bakvänt detta känns att implementera. Men jag tror ändå att det är den bästa lösningen.

Detta berör absolut användaren på ett eller annat sätt. Om användaren vill lägga upp en ny bokningsbar lokal så måste en tidszon för denna anges (såvida inte BAS förutsätter samma tidszon för alla lokaler, som i ljniklas exempel ovan).

I Aveny kan man (teoretiskt) styra värmen i både finska och svenska lokaler. Aveny vet idag inte var lokalerna finns. Om standarden kräver en viss tidszon måste vi antingen låta tidszon styras per lokal i Aveny eller så måste alla tider i Aveny bokas i samma tidszon. Vi lägger normalt inte upp lokaler åt våra användare. Därför måste i vårt fall någon användare beröras av detta.

Vi vill ju skapa en öppen och internationell standard. Skall vi verkligen förutsätta att alla framtida BAS kör med samma tidszon internt för alla sina lokaler? Om inte, så kvarstår min senaste fråga.

**Comment by ROWSAB** [comment]
Men detta har fortfarande inte något med användaren att göra. Användaren bokar i Svensk tid, BAS sparar det som ett klockslag, hur det sparas spelar ingen roll. BCS presenterar det som Svensk tid.
Dessutom "konverterar" vi inte tiden. Tiden är UTC i datorn, den konverteras till Svensk tid när den presenteras för användaren i operativsystemet.
Detta handlar om HUR vi ska skicka tiden och om tiden som skickas (oavsett åt vilket håll) ska skickas med sommar/vintertid applicerat.
Att skriva in i en nordisk standard att CET gäller är ju helt galet. I sådana fall måste tiden skrivas ut med vilket tidsförskjutning det är som gäller.
Såhär: 2016-10-03T14:15:14Z+2 annars är det ingen Nordisk standard, då är det endast en standard för dom länder som kör med CET. Finland är ute ur leken då. Så då undrar jag helt enkelt, varför ska vi skicka tider mellan datorer med tidszoner och sommar/vintertider när det är uppenbart att det begränsar standarden. Jag ser ingen som helst logik i det. Och OM vi nu ska göra det så måste vi sätta ett krav på att tidsskillnaden mellan aktuell tid och UTC måste finnas med. Så som tex i dokument v001.
Detta är i grunden det viktigaste beslutet i denna standard, eftersom hela principen med standarden är just att skicka tider mellan datorer. Allt annat är bara tillägg.
Så fundera igenom ordentligt innan ni röstar, för när väl Nivå 1 är spikad så ska det mycket till innan den ändras.
Jag skapar en ny Issue för röstning kring detta.
Svar på Eniac kommer i nästa kommentar.

**Comment by ROWSAB** [comment]
Så hela detta problem kretsar kring att BAS måste lägga in stöd för tidszoner? Vilket jag trodde att man hade.
Men hur ska BCS hantera detta? Ska BCS alltid anta att tiden som kommer från BAS alltid är den tidszonen som lokalen befinner sig i? Inklusive sommar/vintertid? Det är en stor skillnad mellan sättet att se på tid mellan en BAS och BCS. För BCS är tiden absolut. Den vill veta exakt NÄR det ska ringa i klockan. Medan BAS ser tider som en variabel bland andra, såsom Titel och annat. BAS behöver egentligen inte bry sig om exakt vart solen står när det är bokat. På sätt och vis behöver BCS göra det.
Jag skapar en ny issue för röstning kring detta.

**Comment by JEFFBjorn** [comment]
Att det har med användaren är faktiskt självklart.

Om du nu antar att alla tider sparas som UTC i alla led så måste man göra omvandlingar från det som användaren skriver in och även till det som användaren ser. Detta gäller alla led.

Om man nu sparar tiden som lokal tid så behövs ingen omvandling i något steg. Det ända kravet är då att DUC som skall starta och stoppa på tiderna måste veta vilken lokal tid som gäller där DUC står.

Som sagt så förordar vi på JEFF att man skickar i lokal tid i standarden.

**Comment by EniacData** [comment]
@ROWSAB:

> Så hela detta problem kretsar kring att BAS måste lägga in stöd för tidszoner? Vilket jag trodde att man hade.
> - Jag tycker att det är en principfråga. Vi har givetvis inga problem att anpassa Aveny till vad vi än bestämmer.
> 
> Men hur ska BCS hantera detta? Ska BCS alltid anta att tiden som kommer från BAS alltid är den tidszonen som lokalen befinner sig i? Inklusive sommar/vintertid?
> - Jag tycker det. Jag kan inte se att det borde kunna bli problem (men å andra sidan har jag ju ingen erfarenhet av tidsstyrning).
> 
> För BCS är tiden absolut. Den vill veta exakt NÄR det ska ringa i klockan.
> - Svaret är: Eftersom bokaren angav 10:00 vill denne att det skall ringa exakt när klockan i kyrkan slår 10:00 den dagen.
> 
> BAS behöver egentligen inte bry sig om exakt vart solen står när det är bokat. På sätt och vis behöver BCS göra det.
> - Jag förstår det. "Lokal tid" är ju ett mänskligt begrepp och inget datorbegrepp. Det måste ju till syvende och sist skrivas in i datorn. Jag förstår hur förvirrande det blir om den engelske administratören på en engelsk server tittar på 10:00 och det (för honom) egentligen är 12:00. Det måste BCS hantera på något sätt. Men jag tror ändå att det är bättre än alternativet.

**Comment by EniacData** [comment]
För att undvika trassel med datumfält kanske vi skall skicka timme och minut som två integers?

**Comment by ROWSAB** [comment]
Vi har fullt stöd för alla tidszoner i vårt system. Därav vårt problem med hela denna fråga.
Eller så skickar vi Epoch som en UInt64

**Comment by ROWSAB** [comment]
Jeff, för er information så sker den konverteringen alltid när en tid presenteras för dig i datorn. Det trodde jag ni visste eftersom ni var "hårdvaru nära"

**Comment by ljniklas** [comment]
Formatet bör vara en standard så som ISO-8601 eller i Unix Timestamp (Epoch). Detta fanns med som inparameter vilket man önskade tror jag?

**Comment by ROWSAB** [comment]
Håller med niklas. Har försökt säga det hela tiden. Men om vi ska följa ISO-8601 så måste tidszonen stå specificerat. Därmed måste Eniac bygga in stöd för tidszoner.

**Comment by EniacData** [comment]
Det är det näst bästa alternativet, dvs att BCS i frågan skickar med vilken tidszon som gäller för lokalen. Då kan BAS fortfarande arbeta med lokal tid (enklast för användaren), och översättningen sker i interfacet.

**Comment by JEFFBjorn** [comment]
För information till ROWS så kan man faktiskt ställa tiden i hårdvaran. Tiden som sparas i hårdvaran är normalt sett antal sekunder sedan 1970-01-01 och det går utmärkt att spara den svenska tiden i hårdvaran.

Sedan kan man även om man vill slippa alla omvandlingar ändra tiden 2 ggr per år i samband med byte mellan sommar och vintertid.

De personer som programmerar hårdvarunära har inget operativsystem i botten. 

Att tid alltid konventeras när den visas för dig stämmer bara i vissa fall. Den tid som hårdvaruklockan har konventeras till din lokala tidzon om du använder ett OS som gör det, (tror faktiskt att alla OS gör det idag). Tider som är sparade i en databas behöver inte konventeras om man sparat undan lokal tid.

**Comment by ROWSAB** [comment]
Jeff, det är inte rekomenderat att göra så som ni beskriver. Går inte klockan bakåt när du ändrar från sommar till vinterid? Vad händer med alla era timeouts?
Tiden i en processor bör alltid existera som antal sekunder (millisekunder/microsekunder eller annat) och sedan öka med tiden. När tiden ska användas skall sommartid och tidszon appliceras.
Det är bara "bad practice" att ställa klockan på lokal tid. Funkar kanske för ett litet theben ur, men inte på ett övervakningssystem. Det måste ni väl ändå erkänna.

Det är sant att man inte har ett OP i botten. Däremot har ANSI C <time.h> stöd för locales. Och det är det jag syftar på.

**Comment by ROWSAB** [comment]
Eniac, varför är det så fel att skicka Epoch istället för en sträng?

**Comment by JEFFBjorn** [comment]
Att använda timeouts mot systemklockan är inte att rekomendera i något fall. 
Varje gång någon(eller automatik) går in och ställer klockan riskerar man att ändra eller slå ut timeouter.

**Comment by ROWSAB** [comment]
Så sant, men planen är att klockan alltid går rätt sisådär på några sekunder. Annars ringer ju inte klockorna på exakt rätt tid. Att låta användaren ställa klockan är mindre rätt. Automatisk ändring ändrar extremt sällan mer än någon sekund.

**Comment by JEFFBjorn** [comment]
Jag vet att ni hatar MODBUS men MODBUS RTU har en timeouttid på 3 ms för att tala om att meddelandet är slut. Nog ändrar även en automatiskt inställning mer än 3 ms.

**Comment by ljniklas** [comment]
Är det bara jag eller har ni hamnat något off topic nu?

Jag vill förespråka att det är en standard vi ska ta fram. Alltså något som ska gå att använda av andra som inte inkluderar oss tvunget. Att då definiera något så diffust som "lokal tid" känns snudd på lite oprofessionellt kan jag tycka. Bättre att bara sätta att det ska vara i UTC/GMT som redan är befintliga definierade standarder och där det finns mängder med information om vad det är och hur de funkar.

Det samma gäller vilket format som ska användas. Det bör vara i en redan definierad standard och där förespråkar jag (likt Robin) UNIX Timestamp (Epoch).

Varför uppfinna hjulet på nytt när det finns färdiga standarder att använda och som i många fall är enkla att jobba med just för att de är så vedertagna?

**Comment by EniacData** [comment]
@ROWSAB, inget fel på epoch om vi bestämmer oss för det. Det enda jag är emot är att BAS skall tvingas hålla sig med tidszoner helt i onödan. Skickar BCS med önskad tidszon i requesten slipper vi det problemet.
(Kör vi med lokal tid rakt igenom slipper vi också problemet).

**Comment by EniacData** [comment]
@ljniklas, men i detta fall är det ju inte enklare med standarden.
2016-10-03T14:15:14Z+2 eller 1475501325 vs 2016-10-03 14:15
Standarder är bra, men användbarhet är bättre.

**Comment by ljniklas** [comment]
@EniacData: På vilket sätt menar du att "lokal tid" är mer användbart? (Förutom att det är enklare för er i detta fallet)

För det känns inte användbart i mina ögon att behöva skriva en egen lång beskrivning av vad som innebärs med "lokal tid" i just denna standarden. Visst nu är alla vi inblandade i denna tråden införstådda på vad ni syftar på, men vi måste sätta oss i sitsen av att en utomstående (BCS eller BAS) kommer och vill införa standarden i sitt system. Kör vi på "lokal tid" så tror jag risken för att de behöver fråga någon som redan implementerat den om råd är mycket större än om vi helt enkelt definierar att tider ska anges i GMT/UTC. Alltså fallerar lite tanken bakom att ha just en "standard" tycker jag.

Som exempel så använder inte vi UUID över huvudtaget och jag ifrågasatte detta initialt. Efter diskussioner och fleras insynsvinklar så ser jag att det gagnar standarden och samtliga involverade ifall vi använder UUID-formatet på ID:n i standarden, även om detta inte är det absolut enklaste just för mig. Vi måste tänka på det stora hela och jag tycker GMT/UTC är det uppenbart bästa att använda för att alla (nuvarande och framtida) nyttjare av standarden enkelt ska kunna implementera den med minimala felkällor för feltolkningar och missförstånd.

**Comment by EniacData** [comment]
@ljniklas: Lokal tid är mer användbart för användarna i bokningssystemen. För mig som programmerare är det bara olika sätt att se på samma sak. Det är inte det att jag är lat och vill ha enklaste lösningen för mig. Det är en principsak. Jag har försökt uttrycka det flera gånger, men jag tror att vi pratar förbi varandra lite.

Detta är principen jag syftar på:
Tidsangivelsen är ett meddelande från bokaren till t.ex. kyrkklockan. Inget program eller protokoll på vägen behöver bry sig om vad det står, eller än mindre ändra det.

Jämför med ett SMS till vaktmästaren: Ring i klockan 10:20

Kör vi på lokal tid måste vi skriva: "Tiden anges på formatet yyyy-mm-dd hh:nn, och skall vara uttryckt i lokal tid som gäller i aktuell lokal den aktuella dagen."

Du nämner felkällor. Med lokal tid tror jag att dessa blir mindre. 10:20 bokas, 10:20 skickas, 10:20 ringer klockan. Om något går fel kan man lätt se i loggarna om t.ex. 9:20 skrivs in någonstans.
Kör vi på t.ex. GMT så kanske 10:20 bokas, 8:20 skickas, 10:20 ringer klockan.
Går det fel är det två "konverteringar" som måste undersökas.

Användbarhet:
Med lokal tid (när man väl förstått vad detta är) så slipper ett BAS som kör med en och samma tidszon internt införa tidszoner (för ett BAS som har tidszoner spelar det ingen roll). Detsamma gäller på BCS-sidan. Kör man med samma tidszon internt slipper man införa en eller hårdkoda, och vet man redan lokalens tidszon så kan man lagra den inkomna tiden på valfritt format.

**Comment by ROWSAB** [comment]
Men det är ju där vi har problemet Eniac. Du kan inte jämföra en DUC (DataUnderCentral) med en vaktmästare. När två människor pratar, som dessutom känner varandra, så finns det vissa förutbestämda saker. Såsom att all tid vi pratar om är Svensk tid med sommar och vintertid medräknat.
Om du skickar 10:20 till min DUC så måste den veta om du menar. Och ja, i detta läge är det kanske inte några problem för min DUC att kunna ha en inställning som säger att den ska köra på Svensk tid med sommar och vintertid. Men om det är en server så måste tiden vara mer specificerat. Lokal tid går inte att applicera där på samma sätt. I det läget måste servern spara ner vilken tidszon det är som gäller.
Då måste varje enhets klass inneha en variabel som säger att det är tidszon +01 som gäller. Visst det är lugnt, men så fort som vi ska låta en server räkna ner antal minuter till nästa bokning så blir allt det här en helt annat sak. I det läge är det definitivt en fråga om konvertering.
Det jag och Niklas pratar om är ingen konvertering, det är bara ett uttryck för HUR tiden ska presenteras. Vi måste se skillnad på ett klockslag och antal minuter kvar. Vi måste också se skillnad på vaktmästare och DUC. Det är inte förrän vi har A.I som du kan SMS:a DUC:en och säga åt den att ringa i klockorna klockan 10:20 Fram tills dess MÅSTE vi specificera EXAKT vad det är som gäller. Och att i en standardspecifikation komma å säga att det är lokal tid som gäller är i grunden både fel och mer "prone-to-error" än att helt enkelt skicka epoch.
Att skicka en sträng istället för epoch tiden är en annat fråga och där kan jag köpa Jeffs argument att det är lättare att felsöka. Samtidigt så är ju felsökning på protokolnivå inget som kommer att göras varje dag. Däremot kanske det blir så som du säger att någon har bokat fel. Men det är absolut inget konstigt att låta loggen spara ner Svensk tid även om den kommer som UTC. Det är ingen konvertering, det är bara samma tid uttryckt som en sträng med svensk tidszon.
Däremot om jag sparar ner ett klockslag, helt utan information kring HUR den tiden ska tolkas så måste det ske en regelrätt konvertering av tiden.
BCS server kommer att dra bort eller lägga till timmar för att konvertera/korrigera tiden till något som BCS server kan förstå. 

Precis som du skriver Eniac så är detta en principsak. Av princip ska vi INTE applicera tidszon och annat som kräver "konvertering" av tiden.
UTC är själva tiden, svensk/lokal tid är SAMMA tid presenterad med svenska/lokala standarder.
Det är endast när vi får en sträng som är presenterad som lokal tid som vi kommer att behöva konvertera tiden för att ett system ska kunna använda sig av den.
Även om Jeff inte förstår det så sker det en konvertering där, annars kan dom inte räkna ner antal minuter till nästa bokning. Jag har väldigt svårt att tro att dom gör så som man hade gjort om man programmerat java när man är 12 år och helt enkelt tittar på timmen på klockan och om den är samma som det som är sparat så tittar den på minuten. Om den också är samma så ringer man i klockan.
Det funkar lixom inte att göra så. Vi måste konvertera den lokala tiden till samma tidsformat som datorn använder sig av för att kunna räkna ner hur lång tid det är kvar till nästa bokning. Och datorn använder sig av UTC. När du tittar på klockan nere till höger i windows så är den bara uttryckt med svenska/lokala standarder. 
Så om vi nu ska hålla på principen att så få konverteringar skall ske så ska vi ju köra på UTC, för då sker inga konverteringar.
Men jag tycker att vi lägger ner denna diskussion och låter demokratin bestämma.
ROWS har inga problem att rätta sig efter vad som bestäms. Det är bara det att vi anser att standarden är viktigare än varje enskild programmerare. Precis som Niklas säger.

**Comment by ROWSAB** [comment]
PS, förslaget du la om att använda separata integers för timme och minuter är ju samma tanke som att titta på timmen och minuten för att avgöra om det ska vara varmt eller inte.
Och om vi nu ska prata konvertering och risken för fel så är ju det extremt konstigt att tvinga alla BCS att konvertera interger värdet 4 som representerar timme fyra på en specifik dag. Snacka om konverteringar.

**Comment by ROWSAB** [comment]
Nu när detta är spikat så tar jag ett ansvar att skriva ner detta i standarden och släppa en ny draft.
Jag lägger även in det som har diskuterats i dessa Issues.
Jag ska försöka hinna med detta så fort som möjligt.
