### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by hans1run** [ROWSAB/Booking-Nordic-Standard#10]
Hei
Har et scenario vi må ta stilling til hvordan man skal løse. I vårt booking system kan alle lokaler som er booket på en avtale ha en offset i minutter i forhold til selve avtalens tidspunkt. Sånn api er nå returner vi bare en liste med ressurs id'er som er booket på avtalen. Burde vi ha offset med også? Evt så må man returnere samme avtalen flere ganger med ulik tidsinformasjon.

**Comment by JEFFBjorn** [comment]
Hej
För att veta lite hur man skall lösa offseten så kan det vara intressant att veta syftet med att använda offset.
Varför finns funktionen?

**Comment by ROWSAB** [comment]
Det enklaste borde vara så som Eniac kör. Där skickar dom endast tiden som själva lokalen är bokad.
BCS är inte intresserad av själva bokningens tid. Endast när resursen som är själva lokalen är bokad.
Eller förstår jag din fråga fel?

**Comment by hans1run** [comment]
Typisk kan det vær at et lokale skal være opptatt en time før (rigging av lys,lyd) og kanskje en time etterpå (stedning)

**Comment by ROWSAB** [comment]
Ok, då ska ju tiden vara inkl offseten.
Bokad tid = comfort heat

**Comment by ljniklas** [comment]
Vi använder också oss av offset på våra resurser på våra bokningar. Detta är för att resurser rätt ofta ska bokas upp en längre tid än själva bokningen äger rum.

Om vi tar en söndagsmässa som exempel så börjar kanske mässan vid 11:00, så är det denna tiden som bokas upp på bokningen. Lokalen och vaktmästaren behöver dock bokas upp redan från 10:30 då vaktmästaren behöver tillgång till kyrkan för att ställa i ordning och förbereda. Prästen kanske bokas upp 10-15 innan start för att få möjlighet att förbereda sig.

Men jag håller med Robin (ROWS). Även vi returnerar idag bara tiden för själva lokalen, för det är det som BCS bryr sig om.

**Comment by hans1run** [comment]
Man kan ha tilfeller der to lokaler på samme avtale skal ha ulik offset.

**Comment by ljniklas** [comment]
Varje anrop som görs är för en specifik lokal, alltså är det endast tiden den lokalen är bokad som är intressant att returnera.

Givetvis så i listan över ytterligare bokade resurser på samma bokning så bör där kanske finnas med start- och stopptid också då de kan skilja sig från tiden som den "anropade" lokalen är bokad.

**Comment by ROWSAB** [comment]
Jag föreslår att vi kan bortse från den listan med tillhörande resurser i en bokning nu i Nivå 1 och lämnar det till Nivå 2.
Vilket betyder att det endast ska returneras den tiden då lokalen (den begärda resursen) är bokad.
Alltså när det ska vara personer i lokalen.
Det är ytterst viktigt att BCS får information om när det är folk där. Inte när själva förrättningen börjar.
Vi gör så att under bokad tid ignorerar vi fuktstyrningen och kör på komfort värme. Annars kommer systemet brassa på så det luktar bacon för att försöka sänka fukten.

**Comment by ROWSAB** [comment]
Jag kan ta bort den listan i specifikationen inför imorgon också om ni vill?

**Comment by ljniklas** [comment]
Ja, den listan är onödig i nivå 1, håller med.

Bacon <3

**Comment by ROWSAB** [comment]
<img src="http://ghk.h-cdn.co/assets/16/08/980x490/landscape-1456165374-bacon-strips.jpg">

**Comment by hans1run** [comment]
Si at man har to lokaler Kirkerom og Spisesal. BCS sender inn begge to i GetResourceData
En avtale har begge lokalene som ressurser med ulik offset. Når avtalen returneres er det jo ikke noe annet en den listen som forteller hvilke lokaler som skal ha varme?

**Comment by ROWSAB** [comment]
Exempel:

Bokning gjord 12:00 till 13:00
Kirkerom offset -1h och +1h
Spisesal offset -30m och +30m

Då blir det så att när BCS hämtar listan för resursen "Kirkerom" så ska BAS returnera 11:00 till 14:00.
Och när BCS hämtar listan för resursen Spisesal så ska BAS returnera 11:30 till 13:30

Eller har jag missförstått frågan? Norska är inte riktigt min starka sida ;)

**Comment by hans1run** [comment]
Da forutsetter du at du henter GetResourceData for ett og ett lokale

**Comment by ROWSAB** [comment]
Njae, men jo du har rätt.
Det finns en miss där.

**Comment by ROWSAB** [comment]
Vad sägs om att lägga till en "resource" nod i objekten i listan?

Begär två resurser (Kirkrom och spisesal)
{
  “method”: “GetResourceData”,
    “client”: {“
        api”: “1.1 .10”,
        “id”: “9818 d49a - 005 d - 4 a83 - 93 b3 - 9 de04a6a5225”,
        “time”: 1475226019,
        “hash”: “a43074f5bfa356d3be7dda51ef2e4016292743bd”
    },
    “payload”: {”
        dateFormat”: ”string” "start": "2015-05-01",
        "end": "2016-05-01",
        "resources": [
            "5817c100-d599-4f2e-9c25-07e7a64075a0",
            "fe77c299-980e-49a2-82a5-4f42a4cadf34"
        ]
    }
}

Returnerar en lista med båda resurserna och dess resursid.
{
    "status": {
        "code": 0,
        "msg": "ok"
    },
    “server”: {“
        api”: “1.1 .10”,
        “time”: 1475226019
    },
    “payload”: {
        "list": [{
            "id": "afff431b-2835-45a1-9c5e-a100d746ea0c",
            "resource": "5817c100-d599-4f2e-9c25-07e7a64075a0",
            "start": "2015-05-05 11:00:00",
            "end": "2015-05-05 14:00:00",
            ”created”: ”2015 - 05 - 01 11: 00: 00”,
            ”signature”: ”Eva Andersson”,
            "heat": 0,
            "title": "Kirkrom bokad"
        }, {
            "id": "99c42508-0e9c-4eef-af19-d7dbb48f9b27",
            "resource": "fe77c299-980e-49a2-82a5-4f42a4cadf34",
            "start": "2015-05-05 11:30:00",
            "end": "2015-05-05 13:30:00",
            ”created”: ”2015 - 04 - 01 11: 00: 00”,
            ”signature”: ”Eva Andersson”,
            "heat": -1,
            "title": "Spisesal"
        }]
    }
}

**Comment by ljniklas** [comment]
Precis en sådan lösning jag satt och funderade på Robin.
Eller en tydligare gruppering kanske är att göra såhär:

```
{
    "status": {
        "code": 200,
        "msg": "Ok."
    },
    "server": {
        "api": "1.1.10",
        "time": 1475226019
    },
    "payload": [
        {
            "resource": "5817c100-d599-4f2e-9c25-07e7a64075a0",
            "list": [
                {
                    "id": "afff431b-2835-45a1-9c5e-a100d746ea0c",
                    "start": "2015-05-05 11:00:00",
                    "end": "2015-05-05 14:00:00",
                    "created": "2015-05-01 11:00:00",
                    "signature": "Eva Andersson",
                    "heat": 0,
                    "title": "Kirkrom bokad"
                }
            ]
        },
        {
            "resource": "fe77c299-980e-49a2-82a5-4f42a4cadf34",
            "list": [
                {
                    "id": "99c42508-0e9c-4eef-af19-d7dbb48f9b27",
                    "start": "2015-05-05 11:30:00",
                    "end": "2015-05-05 13:30:00",
                    "created": "2015-04-01 11:00:00",
                    "signature": "Eva Andersson",
                    "heat": -1,
                    "title": "Spisesal"
                }
            ]
        }
    ]
}
```

**Comment by ROWSAB** [comment]
Bra idé Niklas!
Jag lägger det som ett förslag.
Blir det bra Rune?
Ni som har invändningar säg till nu gärna.

**Comment by hans1run** [comment]
Det vil fungere ja

**Comment by ROWSAB** [comment]
Är det ok om jag skippar ditt senaste förslag Niklas om att gruppera listan efter resurser?
Jag anser att det blir lite fel om payload kan vi vissa lägen vara ett JSON objekt och i andra vara en JSON array.

**Comment by ljniklas** [comment]
Du har en bra poäng där.

payload borde alltid vara ett object. Så i så fall kanske där bör bara en "nivå" till under payload som är "resources" som är arrayn?

**Comment by ROWSAB** [comment]
mjo, funderade på det. Men blir det inte lite för mycket då? Bara för att sortera det. För min del så har jag inget behov av den typen av separering. Vi kan ju köra det om det är lättare för er (BAS) eller om någon av BCS tycker att det blir lättare att läsa av.

**Comment by ROWSAB** [comment]
Det är denna funktion som kommer att köras oftast, och ju mindre den är ju mindre cpu och bandbredd använder vi ;)
Var mest så jag tänkte.

**Comment by ljniklas** [comment]
Spelar ingen roll för min fel, tänkte det skulle vara lättare för en BCS om ni fick de grupperande. Jag kommer att hämta bokningar för en resurs i taget oavsett om de ska grupperas eller läggas i samma array.

**Comment by ROWSAB** [comment]
Absolut, och det finns ju inget som säger att dom ska komma i kronologisk ordning.
