### ISSUE TITLE
Röstning för att spika Nivå 1 (Level 1)

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#11]
Då var det dags.
Jag hoppas att jag inte har missuppfattat något eller glömt att ändra något som vi hade diskuterat.

Detta är en issue för röstning, så inga diskussioner här. Skapa en ny issue i sådana fall.
Röstningen stänger så fort alla har röstat.
Försök att hinna med det denna vecka.

Ja = Vi låser fast Nivå 1 enligt v1.1.12
Nej = Ytterliga ändringar måste göras.

**Comment by ROWSAB** [comment]
JA

**Comment by JEFFBjorn** [comment]
Nej
När jag läste igenom dokumentet nu så hittade jag två saker.
1. Saknar sidnumrering i dokument
2. Enligt beskrivning sid 12 skall formatet på tider vara “yyyy-mm-dd hh:MM:ss” om man valt string. På sidan 13 exemplet så har man angett tiden med enbart datum "yyyy-mm-dd". En inkonsekvens som kan leda till icke kompatibilitet. Antingen skall vi tillåta båda string-formaten och då skall det stå eller så skall vi bara tillåta ett string-format och då skall exemplet ändras.

**Comment by ROWSAB** [comment]
Sådär.
Jag har uppdaterat v1.1.12 istället för att göra en ny version.

Kan vi rösta om själva Level 1 implementeringen från och med nu.
Formateringar, såsom sidnummer eller om huruvida vi ska ha fet text eller inte i dokumentet är orelevant i dagsläget.

**Comment by JEFFBjorn** [comment]
Jeff röstar Ja
