### ISSUE TITLE
Ny röstning för att spika Nivå 1 (Level 1)

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#12]
Observera ändringen som är gjord med clientKey.

Ja = Vi låser fast Nivå 1 enligt v1.1.13
Nej = Ytterliga ändringar måste göras.

**Comment by ljniklas** [comment]
**Ja**

**Comment by ROWSAB** [comment]
Ja

**Comment by JEFFBjorn** [comment]
ja

**Comment by hans1run** [comment]
Ja

**Comment by ROWSAB** [comment]
Nu är det bara Eniac kvar.
Vad säger ni?

**Comment by ROWSAB** [comment]
Snart spikar vi standarden utan er Eniac.

**Comment by ROWSAB** [comment]
Har nu spikat/låst nivå 1 i standarden.
Ingen ändring är gjord i dokumentet.
Har endast kopierad den senaste pdf versionen till en ny mapp som jag tänkte att vi skulle använda för fastslagna nivåer.
