### ISSUE TITLE
Giltiga tecken

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#13]
Gokväll allesammans!
Jag insåg precis ett ganska stort problem som vi har förbisett.

Såsom det är implementerat nu så får inte kunden använda vissa tecken i titeln och annat eftersom det då förstör json formatet mellan våra servrar. Om tex titeln innehåller ett " så blir det totalfel.

Mitt förslag för att lösa det är att base64encoda all text som kunder kan skriva.

Vilket blir dessa i aktuell standard::
GetCustomerData.payload.customers[x].name <--Eventuellt denna
GetCustomerData.payload.customers[x].resources[y].name
GetResourceData.payload.list[x].signature
GetResourceData.payload.list[x].title

Vad säger ni?
Har ni några andra förslag?

**Comment by ljniklas** [comment]
Detta är inget problem. JSON-standarden talar tydligt om hur detta ska hanteras: [http://www.json.org/](http://www.json.org/).

TL:DR: JSON använder sig av backslash (\\) som escape före tecken som annars hade sabbat strängen och då framför allt dubbelfnutt ("). Även en del andra tecken berörs, men de avhandlas i länken ovan.

**Comment by ROWSAB** [comment]
Ajuste!
Det har du ju helt rätt i.
Dåså, då kan vi lägga ner den här tråden.
Tack Niklas!
