### ISSUE TITLE
Draft 007 från JEFF

### ISSUE THREAD

**Issue by JEFFBjorn** [ROWSAB/Booking-Nordic-Standard#2]
Laddat upp en draft 007 med några småändringar och kommentarer

Kommentera gärna vad ni tycker här i denna issue.

**Comment by ljniklas** [comment]
1. appID bör väl vara samma för ett BCS oavsett BAS, nyckeln som används i hashen gentemot respektive ska dock inte vara publik och således unik per BCS och BAS.

**Comment by EniacData** [comment]
JEFFs kommentar under RESPONSE, list stämmer inte.
Det finns ingen risk att missa bokningar med de angivna villkoren, såvida inte bokningssystemet innehåller bokningar där starttiden är senare än sluttiden.
Antag att starttiden på bokningen i det angivna exemplet är 20160926 1100 och sluttiden 20161002 1300, och man frågar efter bokningar mellan 20160928 0000 och 20160928 2359. Då är villkoret uppfyllt, eftersom 20160926 1100 < 20160928 2359 och 20161002 1300 > 20160928 0000

**Comment by EniacData** [comment]
Ang. JEFFs kommentar under RESPONSE, list.title
Behöver vi en maxgräns? Om både BCS och BAS klarar längre känns det onödigt. Om ett BCS och ett BAS använder standarden, och BCS har en inbyggd begränsning räcker det väl för BCS-leverantören att informera användarna av BAS att titlarna kommer att bli klippta om någon skulle titta på dem i BCS?

**Comment by JEFFBjorn** [comment]
Eniac har helt rätt angående bokningstiderna. Såg fel i villkoren.

//Björn
Jeff Electronics AB

**Comment by ljniklas** [comment]
1. **appID** bör väl vara samma för ett BCS oavsett BAS, nyckeln som används i hashen gentemot respektive ska dock inte vara publik och således unik per BCS och BAS.
2. **Statuskoder**: Jag har tidigare utgått ifrån HTTP kodstandarden när jag bestämt statuskoder. dvs 200 = OK, 204 = No content, 400 = Bad request (fel i indata), 401 = Unauthorized, 403 = Forbidden, 404 = Not found osv. Menar givetvis inte att dessa faktiska HTTP koder ska returneras i HTTP headern utan enbart i fältet responeStatus.success (detta bör kanske döpas om till responseStatus.code eller liknande?). Lista över HTTP koder: [https://en.wikipedia.org/wiki/List_of_HTTP_status_codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
3. Ser inte heller någon anledning till att begränsa list.title i längd. Det kan väl vara upp till BCS-systemen att göra truncate vid behov/hämtning.
4. **Versionsnummer**. Bör vi definiera hur versionsnumret i anropen ska vara formaterat? Med eller utan punkter?

**Comment by ROWSAB** [comment]
Yepp, Eniac har rätt. Det kontrollerade jag innan jag ändrade från mitt till deras. Logiskt sätt blir det rätt oavsett.
I övrigt tycker jag att era ändringar ser bra ut.
1. Tvinga HTTPS är en bra grej. Dock ska vi inte använda HTTPS som den enda säkerheten eftersom den har sina brister.
2. Ang. appID  håller jag med Niklas. Däremot borde vi omformulera er text. Login med password är fel eftersom det endast är ett unikt id. hashningen som kommer snart som förslag är inte att se som password. Jag fixar förslag nu innan lunch
3. Smart av Niklas att köra HTTP koder. Jag har en känsla av att HTTP status koderna räcker långt. Vi kanske ska lägga till att alla koder som är < 0 är unika felmeddelanden från varje enskild BAS och används för debugging vid tokfel. Låter bra?
4. Datumets format är ett bra förslag.
5. Anser inte heller att vi ska begränsa title. Det kan BCS filtrera i sådana fall.

**Comment by JEFFBjorn** [comment]
Svar till Niklas på LJ
1. Tycker inte att appID skall vara samma för BCS oavsett BAS. för om så är fallet så kan BAS(LJ) ta appID och skicka den till en annan BAS(Eniac) och få ut data från dem. Inte OK enligt mig.
2. Att använda statuskoder från HTTP kodstandarden tycker jag är en bra ide. Finns ingen anledning att hitta på en egen standard.
3. Har ingen aning varför ni vill kunna skriva titlar som är hur långa som helst. Dock är det inga problem att trunkera om den är för lång. Behöver vi definiera vilka tecken som är tillåtna. Vet att när vi anlitade en firma för att göra ett penetrationstest på vår utrustning så prövade de att skicka en NULL-byte för att få fram en krash eller otillåtet förfarande.
4. Tycker också att formatet på versionsnummret bör definieras.

//Björn
Jeff Elektronics AB

**Comment by ljniklas** [comment]
Björn:
Då nyckeln som ska användas i hashen är unik per BCS och BAS så kommer jag från LJ inte kunna anropa Eniac med ert appID för jag vet inte om vilken nyckeln ni fått av Eniac till ert appID från dem.
Man skulle kunna säga att det är samma "användarnamn" för alla BCS till alla BAS men olika "lösenord".

**Comment by ROWSAB** [comment]
Håller helt med Niklas i denna fråga.

**Comment by ROWSAB** [comment]
Ang. skicka en null byte så kan det omöjligt bli ett problem eftersom NULL = slut på sträng. Då blir inte nog med att JSON blir icke valid, så blir också strängen kortare. Den slutar alltså där NULL byten finns.

Versionsnummer tänkte jag att det skulle vara en vanlig UInt som vi incrementar när det finns behov av det. Tycker inte att vi ska inkrementa den för varje sub version av standarden. Eftersom varje ändring inte nödvändigtvis förstör bakåtkompatibiliteten i kommunikationen.

**Comment by ljniklas** [comment]
Ang. versionsnummer: Finns där inte en logik i att använda samma versionsnummer i anropet som på dokumentet/standarden? Låt säga att jag skulle gjort ett anrop mot den nu senaste versionen så skulle jag skickat in strängen '007'? Hade vi gått upp och kallat första spikade versionen för 1.x.x så hade man givetvis haft kvar fältet som en UInt och skickat in t ex 100, 102 osv osv.

**Comment by JEFFBjorn** [comment]
Svar till Niklas på LJ
Du får ursäkta min okunnighet när det gäller web-programmering. Mer van vid maskinnära programmering.
Jag vill dock ställa frågan. Behövs ytterligare en kryptering över huvud taget?
Som jag ser det så används HTTPS är det som skickas fram och tillbaka redan krypterad och är appID unik och inte återanvänd så kan appID användas som både användarnamn och lösen.

Sedan skulle jag vilja fråga hur vet BAS vilken nyckel som skall användas. Det måste vara olika nycklar för olika BCS. om jag läst er mail-diskussion så kommer även appID krypteras med nyckeln.

//Björn
Jeff Electronics AB

**Comment by ROWSAB** [comment]
Ang. versionsnummer så spelar det mindre roll för min del. Jag brukar använda dessa versionsnummer i varje request för att försäkra mig om att jag ska kunna ha en möjlighet att "tok ändra" requesten utan att gamla enheter ballar ur totalt. Men versionsnummer på dokumentet kan vi likväl använda.

Jeff, HTTPS är inte den enda säkerheten ni kan luta er på. HTTPS handlar om förtroende. Det är mååååånga i ledet som du ska ha förtroende för.

Tanken med nyckeln är att den ska bli tilldelad en BCS av BAS vid första anslutning.

**Comment by ljniklas** [comment]
Hade precis skrivit ett svar till Björn, men du hann före Robin, så läs ovan Björn.

**Comment by ROWSAB** [comment]
Jeff: Ang. HTTPS

Har inte läst exakt denna, googlade och tog första som handlade om det jag letade efter.

http://arstechnica.com/security/2015/02/lenovo-pcs-ship-with-man-in-the-middle-adware-that-breaks-https-connections/

**Comment by hans1run** [comment]
Hadde det ikke vært en ide å ha versjonsnummer i url'en istedenfor som en parameter i requesten.?
For eksempel. https://basurl/api/v1/method
http://stackoverflow.com/questions/389169/best-practices-for-api-versioning

**Comment by ROWSAB** [comment]
Nej, jag tycker inte att vi ska använda URLen för versionsändring.
URLen bör vara samma, alltid.
Och metoden bör inte vara med där heller.

**Comment by ljniklas** [comment]
Hans: Jag lyfte frågan om att sätta en standard på hur URL:en ska se ut men efter diskussion med Robin så var vi överens om att det är bättre vi låter URL:en vara helt valfri och alla inparametrar skickas som POST-data. Detta är givetvis öppet för diskussion, men det blir enklare för oss BAS-system att implementera standarden ifall vi inte behöver tillhandahålla en specifik URL. Plus att som Robin säger, för BCS-systemen så är det bättre om URL:en alltid är samma.

**Comment by ROWSAB** [comment]
Ja, eftersom tex Eniac kör med egna servrar för varje kund så blir det lite problematiskt om versionsnummret finns med i URLen. Eftersom en uppdaterad BCS kommer att anropa en URL som inte finns i BASens vetande och BCS kommer att få tillbaka 404. (Till och med GIPen kan skapa problem här)
Men det är detta som blir lite fel också om vi kör med dokumentets nummer. Om BCS har v009 och BAS har v008, då bör ju BAS svara med fel "okänd version", men i själva verket är inget ändrat som kan påverka just den requesten/metoden.

**Comment by ljniklas** [comment]
Satt och funderade över detta precis Robin, att det är som du säger inte alla versioner som är "major" eller påverkar speciellt mycket. Speciellt inte om det bara är definitionen av standarden som är ändrad, ingen funktionalitet alls. Det finns två lösningar på detta som jag ser det.
1. Antingen så är versionsnumret på dokumentet helt fristående från versionsnumret på anropen.
2. Första nivån i versionsnumret är vilken nivå. Första nivån är alltså 1. Nästa nummer är senaste versionen på anropen, låt säga 2. Sista numret är vilken version/revision av dokumentet inom ovan nämnda version, låt säga 15. Resultatet blir att versionnumret blir 1.2.15. Det ända som styr vad som returneras av BAS-systemen är de två första nivåerna (1.2). Alltså blir resultatet det samma om BCS skickar in 1.2.3 eller 1.2.15. Hoppas ni hänger med hur jag tänker?

**Comment by ROWSAB** [comment]
Låter som en mycket bra idé! Så kan vi ju köra.

**Comment by EniacData** [comment]
Oavsett hur vi gör med versioner bör vi ha en metod som aldrig ändras och som svarar med vilken (högsta) version BAS stöder. Annars vet inte ett BCS som implementerat en viss version om det kan börja använda denna.

Eller så kan standarden kanske kräva att om BAS får en request med för hög version så måste det svara felkod och vilken version som önskas.

**Comment by ROWSAB** [comment]
Absolut. Det kanske behövs en ny metod som BCS kan anropa för att få mer information om BAS?

**Comment by ljniklas** [comment]
Ja, ett helt öppet anrop som returnerar högsta tillgängliga version, samtliga tillgängliga versioner mm är ingen dum idé!

**Comment by ROWSAB** [comment]
Allt detta är implementerat nu förutom hash förslaget. Har inte haft tid att göra det än tyvärr.
Jag följde inte standarden för ändring men hoppas att ni samtycker till dom ändringarna jag har gjort.
Detta för att snabba upp processen lite så att vi kan spika nivå 1.
Om ni har några invändningar på det som är ändrat, skapa en Issue per sakfråga.
