### ISSUE TITLE
appHash

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#3]
Jag försöker få fram ett förslag på hashningen.
Men jag har svårt för att hitta en bra balans mellan säkerhet och enkelhet.
Vi kan göra detta toksäkert men frågan är om det blir för avancerat då.
Annars kan vi göra det enklare att implementera men då kommer det att finnas kryphål.
Så frågan är om ni har några funderingar kring detta.

Hur ser ni på att jobba med byte data?
Eller ska vi hålla oss till enbart strängar?
En "incremental" räknare är bra så som Eniac sa, men det skapar problem om BCS behöver ha fler än en server som hämtar från samma BAS server. Någon som har en enkel lösning på det?

Jag har ett "nästan" färdigt förslag men det finns vissa problem med den.
Bland annat skapar den endianess problem, som måste lösas med htonl/ntohl vilket kan bli för komplicerat för vissa. Sen blir incremental värdet ett problem för ROWS eftersom vi inte har en stor server som gör allt.
I förslaget har jag tagit fram ett exempel i ANSI C som ni kan ta del av om ni vill.

Så frågan är HUR avancerat ska vi göra detta?
Kan vi acceptera att det finns luckor i säkerheten?

**Comment by ljniklas** [comment]
Som jag nämnde för dig på telefon Robin, så kan jag tycka att vi inte behöver sikta allt för högt nu initialt. Den data som skickas i nivå 1 är ändå inte så känslig anser jag.
Bättre i så fall att utvärdera säkerheten och öka den vid behov på kommande nivåer efterhand som mer och mer känslig data läggs till.
Så initialt så ser inte jag några problem med att det inte är 100%, så länge det inte är för lätt för ev. intrång.
Jag hade även velat ha ett förlag att granska för att kunna svara på hur svårt/enkelt det är för mig att implementera.

**Comment by ROWSAB** [comment]
Ok tack för snabbt svar.
Jag la upp en ny branch som heter appHash.
Det är som sagt inte helt klart eftersom jag stötte på patrull.
Planen var att lägga ihop count och systemTime och hash till en byte buffer och sedan base64 koda det till en appHash variabel som skickas med. Då kan BAS ta den byte datan, få ut count och systemTime och kontrollera att hashen stämmer.

**Comment by ROWSAB** [comment]
Kände också att detta kanske är en enkel match för mig som jobbar i ANSI C, men det kanske är onödigt krångligt för er som jobbar i php och annat.

**Comment by EniacData** [comment]
Jag föreslår att BCS genererar en GUID för varje fråga (istället för count).
Denna sha-256-hashas med 1) ett hemligt AppID som BCS och BAS känner till, och 2) med en timestamp.
GUID, timestamp och hash skickas med som parametrar. BAS kan då verifiera att frågan kommer från rätt AppID och att ingen kopierat någon tidigare fråga (BAS behöver spara tidigare GUIDs i t.ex. en timme), samt att frågan inte är mer än en t.ex. 15 minuter gammal (vi får anta att systemens klockor går någorlunda rätt).

**Comment by ROWSAB** [comment]
Bra förslag!
Kan vi köra på SHA1 istället?
Det är lite lättare för min lilla 200mhz unix dator att generera.

**Comment by ROWSAB** [comment]
Eller till och med HMAC-SHA1? Den ska tydligen vara lite svårare att kracka.

**Comment by ljniklas** [comment]
HMAC-SHA1 är inga problem för mig i alla fall (inte HMAC-SHA265 heller). Låter bra annars.

**Comment by EniacData** [comment]
Eftersom det bara behöver hålla max en timme så räcker nog t.o.m. CRC32! Välj den som funkar bäst.

**Comment by hans1run** [comment]
HMAC-SHA1 bør være sikkert nok
