### ISSUE TITLE
Röstning: Tidszoner

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#4]
Denna Issue handlar om röstningen kring hur tiden skall skickas mellan systemen.
Det finns två val att göra här, kommentera ert val.
Denna röstning är öppen i 7 dagar och under dessa 7 dagar kan man ändra sin röst hur många gånger man vill. Redigera då ert inlägg. Endast ett inlägg per företag får förekomma!
Röstningen avslutas 2016-10-10 15:00

Välj mellan:

VAL 1. Tiden skrivs ut som en sträng utan någon förklaring kring vilken tidszon det gäller. Både BCS och BAS måste ta ett antagande att tiden som står skriven är lokal tid för aktuell byggnad. Om sommar och vintertid används skall tiden inkludera även detta.
Exempel:
Tid som står skrivet i responsen är "2016-10-10 14:00".
Det innebär att det är bokat klockan 14:00 CET med sommartid om lokalen befinner sig i Sverige. 
Alltså 2016-10-10 12:00 UTC
Alltså 2016-10-10 14:00 CET (+2 eftersom det fortfarand är sommartid)

Om lokalen befinner sig i Finland så är det 14:00 finsk tid som gäller. 
Alltså 2016-10-10 11:00 UTC
Alltså 2016-10-10 13:00 CET

VAL 2. Tiden skrivs ut som en sträng med tidszon GMT/UTC. Alltså +0. Sommar och vintertid är inte applicerat i strängen.
Alltså 2016-10-10 14:00 UTC
Alltså 2016-10-10 16:00 CET

**Comment by JEFFBjorn** [comment]
JEFF förordar och röstar  VAL 1

**Comment by ljniklas** [comment]
LJ förordar och röstar VAL 2.

**Comment by ROWSAB** [comment]
ROWS röstar VAL 2

**Comment by EniacData** [comment]
Eniac röstar VAL 1

**Comment by hans1run** [comment]
Røstningen stenger 2016-10-10 15:00, er dette lokal tid eller UTC? :)

**Comment by ROWSAB** [comment]
Haha Rune! Jag skrev först CET efter, men tog bort det.
Vad röstar du?

**Comment by hans1run** [comment]
Agrando stemmer på forslag 2

**Comment by EniacData** [comment]
53 minuter kvar. Verkar mörkt för 1-sidan!

**Comment by ROWSAB** [comment]
Yepp, nu är det spikat. Vi kommer att köra med GMT som tidszon och utan sommartid.
Det innebär att BAS ska skriva ner UTC tiden av datum klassen.
För BCS innebär det att man ska mata in tiden som UTC i datum klassen.
Vill man sedan spara ner det som "lokal" tid eller "Svensk tid med sommartid" så ska klassen sparas ner som localTime. Alla språk har stöd för detta. Inkl ANSI C.
