### ISSUE TITLE
status.code - HTTP-koder?

### ISSUE THREAD

**Issue by ljniklas** [ROWSAB/Booking-Nordic-Standard#5]
Här föreslog jag användning av HTTP statuskoder ([https://en.wikipedia.org/wiki/List_of_HTTP_status_codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)) och fick positiv respons (200? ;-)). Robin föreslog att statuskoder utöver de som ryms i HTTP skulle vara under negativa (< 0).

Varför uppfinna hjulet på nytt? Eller HTTP-koderna kanske inte är tillräckligt applicerbara?

**Comment by ROWSAB** [comment]
Ja juste.
Jag ber om ursäkt, men jag glömde nämna det.
Jag skrev först in i standarden att det skulle vara HTTP status coder.
Men när jag skulle skriva in att en viss kod skall returneras av BAS när BCS skickar för hög versionsnummer så hittade jag ingen bra HTTP kod.
När jag gick igenom listan med HTTP koder så tyckte jag inte riktigt att dom skulle vara applicerbara i våra sammanhang.
Då tänkte jag att man likaväl kan applicera standard HTTP koder i själva HTTPt istället där det är lämpligt.
404 går typ inte att applicera på json:et och 500 kan likaväl och lär ju oavsett komma i HTTPn automatiskt när man har gjort tokfel i asp.net eller vad man nu använder.

Den enda jag såg som skulle kunna användas var typ 401 Unauthorized och på sin höjd någon till.

Eller tänker jag fel?
Jag är helt öppen för förslag.

**Comment by ljniklas** [comment]
Det är lite det som är det fina med HTTP-koder, att vi kan fylla på med egna där det behövs. Längst ner i listan så finns där koder som är skapade av andra system som inte är "officiella".

Jag föreslår något i still med:

### Success
- **200** = OK _(All is good and data returned as requested.)_
- **201***\* = Created _(Data received and processed.)_
- **202***\* = Accepted _(Data received and are still being processed.)_
- **204** = No Content _(Request OK but no data returned.)_
- **299** = OK Deprecated _(Same as 200 except the method will be removed in next level. Alternative method might be suggested in status.msg.)

### Client Error
- **400** = Bad Request _(Invalid JSON in request.)_
- **401** = Unauthorized _(Unknown appId or invalid hash.)_
- **405** = Method Not Allowed _(Requested method does not exist.)_
- **409***\* = Conflict _(Sent data already exist.)_
- **410** = Gone _(Method does not exist anymore. Must have returned 299 in previous level.)_
- **418** = I'm a teapot _(Because reasons.)_
- **460** = Level Version Out Of Range _(Requested level version not yet implemented.)_
- **461** = Method Version Out Of Range _(Requested method version not yet implemented.)_

### Server Error
- **500** = Internal Server Error _(Fatal error in BAS. Further debug error code may be added to status.msg.)_

*\* Dessa koder kanske inte behövs nu fast möjligen i kommande nivåer när BCS:s ska börja skicka tillbaka data till BAS:s.

**OBS!** Dessa koder ska **ej** skickas med i svarets header som faktiskta HTTP-koder då vissa koder (t ex 204) resulterar i att body-delen av svaret totalt ignoreras. Dessa koder ska endast sättas i svaret under status.code och HTTP-koden i headern ska vara 200.

**Comment by ROWSAB** [comment]
Bra tänkt! :D
Har du tid att uppdatera dokumentet?

**Comment by ljniklas** [comment]
Absolut, det är fixat nu. Hoppas jag gjort rätt :)
