### ISSUE TITLE
Byta namn på appId och hash

### ISSUE THREAD

**Issue by ljniklas** [ROWSAB/Booking-Nordic-Standard#6]
Som jag förstod det så lånade Robin detta uttryck (`appId`) från något annat sammanhang och jag tycker inte det appliceras speciellt bra i vårt fall. (Det har redan rått viss förvirring gällande vem som `appId` tillhör.)
Ett annat argument för att appId är dumt att använda är att det faktiskt förekommer appar (applikationer, applications) i båda ändarna av standarden.
Jag föreslår att vi kallar det något i still med `clientID` eller kanske `bcsID`.

Föreslår även att vi kallar hashen för antingen `accessToken` eller möjligtvis bra `token`. Mest för att det är mer eller mindre praxis i många angra API-lösning, i alla fall som jag jobbat med.

Givetvis öppen för förslag här!

**Comment by ROWSAB** [comment]
Jag gillade clientID och token.

**Comment by ROWSAB** [comment]
Glömde token. Körde hash nu. 
Om ni vill att det ska heta token, ta upp det i den andra issue:n. (clientHash)
