### ISSUE TITLE
Hva gjenstår å bestemme?

### ISSUE THREAD

**Issue by hans1run** [ROWSAB/Booking-Nordic-Standard#7]
Hei
Vi trenger å få satt denne standarden snart da vi har kunder som venter på å ta i bruk integrasjonen.
Vi har allerede implementert draft 1. Og vil så fort den ferdige standarden er bestemt, starte implementering av denne. Drøyer det mye lengre, så må vi gå videre med det vi allerede har implementert.
Er det noe annet en access token som det gjenstår å ta beslutning på?

mvh
Rune

**Comment by ROWSAB** [comment]
Tjenare.
Ja det är nog bara hashningen som är kvar att specificera.
Jag försöker lämna in ett förslag imorgon också kan vi ta nästa vecka att diskutera eventuella ändringar.
Låter det bra allesammans?

**Comment by JEFFBjorn** [comment]
Hej

Vi hade ett samtal med Rune och är överens med Agrando om att vi måste få klart en release av standarden så snart som möjligt.

Robin, det låter bra att du lämnar ett förslag i morgon, ser fram emot detta förslag.

MVH
Björn 
JEFF Electronics

**Comment by ROWSAB** [comment]
FYI
Jag fick inte tid till detta i fredags. Jobbar på det nu istället.
