### ISSUE TITLE
clientHash

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#8]
Nu har jag laddat upp ett förslag på clientHashning.
Denna issue är till för diskussioner kring clientHashningen.
Om inga diskussioner har startat innan onsdag så sätter jag igång en röstning för att spika standarden.

**Comment by ROWSAB** [comment]
PS, jag har lagt ett C exempel i denna commit också. (/draft1/Examples/ANSI C/clientHash/)
Varsågoda.

**Comment by JEFFBjorn** [comment]
Följande text finns:
"The secret key is a UUID generated by the BCS and passed to BAS together with the clientID upon
the first contact."
Kan du specificera vad du menar med det. Skall BCS skicka med nyckel och clientID i första requesten?

**Comment by ROWSAB** [comment]
Mjo, vet inte riktigt hur jag ska skriva det.

Men den hemliga nyckeln ska aldrig skickas via API.
Secret key och clientID skickas till BAS när man gör den första uppkopplingen.
Alltså första gången man har en gemensam kund.
Och det skickas via mail eller via någon annan mer säker anslutning.
Tanken är att det bara ska behöva skickas en gång. Och det är upp till vardera parter att lösa det.
Den delningen finns inte med i standarden.

Har du några förslag på hur det ska specificeras i dokumentet på engelska?

**Comment by ljniklas** [comment]
Instämmer att en lite tydligare definition av hur utbytet av clientID och nyckeln ska göras initialt. I alla fall specificera att detta sköts utom standarden som du skrev i din text här ovan. T ex:
"The secret key is a UUID generated by the BCS and given to BAS (through email or other form of external communication) together with the clientID before any methods can be called."
Bara ett förslag, går säkert att förfina och förtydliga ytterligare!

Jag tycker fortfarande att "token" är att föredra framför "hash", så om dokumentet ändå ska uppdateras så kanske det är enkelt ändrat?

Sedan sitter jag och funderar lite kring systemTime i hash-meddelandet och att där ska tillåtas en felmarginal på +-10 minuter. Det i sig ser jag inga problem med, utan snarare det faktum att systemTime anges i epoch (sekunder). För då HMAC-SHA1 är en envägskryptering så kan vi som BAS inte "packa upp" meddelandet och utläsa av BCS angivet systemTime. Och om inte min måndagsmatte sviker mig så skulle vi potentiellt behöva generera upp till ca 1 200 (60 \* 20. 60 sekunder på en minut. +-10 minuter = 20 minuter.) hashningar att jämföra mot vid validering av angiven hash. **Är detta verkligen det bästa?**
Borde inte ett format av systemTime som går ner till max minutnivå vara mer optimalt? Då landar vi istället på ca 20 möjliga godkända hashningar, vilket känns rimligare tycker jag. Om detta görs genom att vi använder en egen variant av epoch som är antalet minuter från 1970-01-01 00:00 UTC eller om vi ska köra det i ett mer läsligt format likt "2016-10-31 10:23" UTC eller något annat låter jag vara öppet för förslag.
Som sagt måndag morgon och tänker jag fel här så rätta mig gärna.

**Comment by ROWSAB** [comment]
Uppdaterar dokumentet med typ ditt förslag.
Ändrar till token.
Njae, asså eftersom vi skickar med den systemTime som användes vid hashningen så behöver BAS endast göra en hashning.
Tiden är till för att låta BAS avgöra om hashnyckeln är på tok för gammal = risk för att en hacker återanvänder samma hash nyckel.

**Comment by ljniklas** [comment]
Givetvis, missade att det skickas med som en egen parameter! Då är det inget problem klart.

**Comment by ljniklas** [comment]
Annars ser förslaget på hash/token väldigt bra ut, bra jobbat Robin!

**Comment by ROWSAB** [comment]
Tack, satte klockan på 05:00 idag för att hinna med det ;)

**Comment by hans1run** [comment]
Det ser bra ut, bra jobbet.
