### ISSUE TITLE
payload och annat.

### ISSUE THREAD

**Issue by ROWSAB** [ROWSAB/Booking-Nordic-Standard#9]
Denna issue är för alla andra ändringar jag gjorde tillsammans med clientHashningen.
Om ni har några invändningar kring något av det (som inte berör clientHash) så får ni ta upp det här.
Om inga invändningar är gjorda innan onsdag så kommer dessa grejer även att spikas med röstningen på onsdag.
Jag vet att detta är lite snabbt inpå, men vi behöver göra färdigt Nivå 1 så fort som möjligt.
Det finns en hel del kunder som väntar på detta.

**Comment by JEFFBjorn** [comment]
Den nya uppdateringen börjar se riktigt bra ut.

Vad jag ser är att det står appID på flera ställen. clientID på vissa ställen. Är inte detta samma? Om så borde man byta alla appID till clientID.

//Björn

**Comment by ROWSAB** [comment]
Gött att du gillar det.
Jo, min tanke var att allt skulle bytas till clientID.
Verkar onekligen ha glömt några.
Jag ordnar det snarast.

**Comment by ROWSAB** [comment]
appKey ska givetvis vara clientKey. Men secret key är något annat.

**Comment by ljniklas** [comment]
I stycket:
"All ID values must be valid GUID/UUID string.
An exception is the instance id for every booking.
The ID must have the format as a GUID/UUID but the generation of the id does not need to follow the UUID standard."

...så skulle jag önska att meningen "An exception is the instance id for every booking." plockas bort då det är fler ID:n än bara de för varje enskild bokning som inte behöver genereras enligt standarden för UUID/GUID så länge det är i det formatet. Detta tycker jag meningen efter förklara bra nog.

**Comment by ljniklas** [comment]
PS. Jag tror du använt fel färg för din ändringar Robin, det är Eniac som är grön egentligen väl?

**Comment by ROWSAB** [comment]
Sant.
Ja jag vet, vette fasen vad som händer men jag försöker ta bort ALL färgmarkering.
Men den kommer tillbaka som ett brev på posten så fort jag stänger och öppnar dokumentet igen.
Tror det är en bugg i LibreOffice.

**Comment by ROWSAB** [comment]
I pdf:en är all färg borta så som det var tänkt.
